application: pixel-life
version: 1
runtime: python
api_version: 1

handlers:

- url: /pixellife/stylesheets
  static_dir: stylesheets

- url: /pixellife/images
  static_dir: images

- url: /pixellife/javascripts
  static_dir: javascripts

- url: .*
  script: main.py
